# Generated by Django 4.1.7 on 2023-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reply_helprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.TimeField(),
        ),
    ]
