# Generated by Django 4.1.7 on 2023-02-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='helprequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.helprequest'),
            preserve_default=False,
        ),
    ]
