# Generated by Django 4.1.7 on 2023-02-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_reply_helprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='helper',
        ),
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.expressions.Case, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='phone_number',
            field=models.CharField(max_length=64),
        ),
    ]
