# Generated by Django 4.1.7 on 2023-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_helper_email_remove_helper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(max_length=64),
        ),
    ]
